### ISSUE TITLE
Override the check for Catalyst version

### ISSUE THREAD

**Issue by collinj22** [curlyboi/hashtopus-agent#2]
Hi,
I was wondering if there was a way the bypass the Catalyst version check, my computer is running version 15.7 and oclhashcat runs fine with the --force command, but the check won't let me use the agent. Thanks

**Comment by curlyboi** [comment]
i suppose i could add this feature
Dne 15. 8. 2015 22:37 napsal uživatel "collinj22" <notifications@github.com

**Comment by collinj22** [comment]
Thanks I would appreciate it.

**Comment by curlyboi** [comment]
Solved in 0.9.8
