### ISSUE TITLE
Not Functioning windows 8.1

### ISSUE THREAD

**Issue by ghost** [curlyboi/hashtopus-agent#3]
Windows 8.1 64-Bit system seems to return this:
"This app can't run on your PC"

Do you have any idea what could have caused this?
I downloaded the hashtopus.exe from the agent deployer

**Comment by ghost** [comment]
could you recompile it some way to not make the program a 16bit based system but a 32bit based one instead? Or seperate download +detection?

**Comment by curlyboi** [comment]
it’s a 32/64 .NET exe from visual studio 2010.

please check if the exe doesn’t contain garbage at the beginning (like php errors etc)

**Comment by ghost** [comment]
It seems to recognize it as a 16bit program for some reason

**Comment by ghost** [comment]
It seems that this problem only occurs on Windows 8.1 64-bit.
Could you check it out?

**Comment by ghost** [comment]
re-opening thread since you don't seem to look at existing issues
