### ISSUE TITLE
64bit processor compatibility

### ISSUE THREAD

**Issue by ghost** [curlyboi/hashtopus-agent#4]
This is something that IS happening.
My PC has a x86-64 processor and that's probably the reason why it can run the program.
But my new laptop has a 64bit processor and can't run any 32bit applications is what I believe to be the issue.

Could you make it so we can download both a 32bit and a 64bit version of hashtopus?

**Comment by curlyboi** [comment]
i am pretty busy these days, i will compile two exes tomorrow and post them
Dne 27. 8. 2015 22:57 napsal uživatel "NullPatrol" <notifications@github.com

**Comment by ghost** [comment]
Alright, I understand.
I'm not sure where you posted them (if you have yet) but I'll take a look

**Comment by curlyboi** [comment]
Didn't make it.

There you go: http://files.100dola.eu/1441005902

2015-08-30 14:52 GMT+02:00 NullPatrol notifications@github.com:

**Comment by curlyboi** [comment]
Was this binary helpful?

**Comment by ghost** [comment]
I was indeed able to resolve the problem, due to trying multiple things I am unsure if it's caused by the new binary or the other solution.

**Comment by curlyboi** [comment]
Ok, closing.

EDIT: aha, it was already closed :D
